#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

readonly REPO="z0horizon/ip-discovery"
readonly CRATES_USER_AGENT="ip-discovery-release-script/1.0 (https://github.com/$REPO)"
readonly NODE_ARTIFACT="node-bindings-all"
readonly WORKFLOW="publish.yml"
readonly EXPECTED_BINDINGS="
ip-discovery.darwin-arm64.node
ip-discovery.darwin-x64.node
ip-discovery.linux-x64-gnu.node
ip-discovery.win32-x64-msvc.node"

DRY_RUN=false
YES=false
SIGN_TAG=false
TEMP_DIR=""

log() { printf '[release] %s\n' "$*" >&2; }
die() { printf '[release] ERROR: %s\n' "$*" >&2; exit 1; }
cleanup() { [[ -z "$TEMP_DIR" ]] || rm -rf -- "$TEMP_DIR"; }
on_error() {
  local status=$?
  printf '[release] FAILED at line %s (exit %s)\n' "${BASH_LINENO[0]}" "$status" >&2
  exit "$status"
}
trap cleanup EXIT
trap on_error ERR

usage() {
  cat <<'EOF'
Usage: scripts/release.sh <command> <version> [options]

Commands:
  check      Validate versions, Git state, CI, and run local release gates
  artifacts Run GitHub's Node build and download all native bindings
  publish    Publish ip-discovery, ipd, then the npm package (resume-safe)
  tag        Create/push v<version>, then watch cargo-dist create the release
  verify     Verify crates.io, npm, GitHub Release, and Homebrew
  all        Run check, artifacts, publish, tag, and verify

Options:
  --dry-run   Print mutating commands without running them
  --yes       Skip typed confirmations for publish/tag operations
  --sign-tag  Create a GPG-signed tag (default: annotated tag, no GPG needed)
  -h, --help  Show this help

The version must already be updated in all manifests and CHANGELOG.md. Registry
publishing remains local by design; the script never stores or uploads tokens.
EOF
}

run_mutation() {
  if [[ "$DRY_RUN" == true ]]; then
    printf '[dry-run]'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

require_commands() {
  local missing="" command_name
  for command_name in "$@"; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
      missing="${missing} ${command_name}"
    fi
  done
  [[ -z "$missing" ]] || die "Missing required commands:${missing}"
}

validate_version() {
  [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$ ]] || \
    die "Invalid SemVer version: $VERSION"
}

manifest_version() {
  sed -n 's/^version = "\([^"]*\)"/\1/p' "$1" | head -n 1
}

json_version() {
  node -e 'process.stdout.write(require(process.argv[1]).version)' "$(pwd)/$1"
}

assert_versions() {
  local file actual
  for file in Cargo.toml ipd/Cargo.toml node/Cargo.toml; do
    actual=$(manifest_version "$file")
    [[ "$actual" == "$VERSION" ]] || die "$file has version $actual; expected $VERSION"
  done
  for file in package.json node/package.json; do
    actual=$(json_version "$file")
    [[ "$actual" == "$VERSION" ]] || die "$file has version $actual; expected $VERSION"
  done
  grep -Eq "ip-discovery = \{ version = \"(\^|~)?${VERSION%.*}(\.|\")" ipd/Cargo.toml || \
    die "ipd/Cargo.toml dependency does not accept ip-discovery $VERSION"
  grep -Fq "$VERSION" CHANGELOG.md || die "CHANGELOG.md does not mention $VERSION"
}

assert_clean_main() {
  local status branch head upstream
  status=$(git status --short)
  if [[ -n "$status" ]]; then
    if [[ "$DRY_RUN" == true ]]; then
      log "[dry-run] Warning: Worktree is not clean:"
      printf '%s\n' "$status" >&2
    else
      printf '[release] ERROR: Worktree is not clean:\n%s\n' "$status" >&2
      exit 1
    fi
  fi
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] Skipping branch and upstream check (currently on $(git branch --show-current))"
    return 0
  fi
  branch=$(git branch --show-current)
  [[ "$branch" == "main" ]] || die "Release must run from main, currently: $branch"
  upstream=$(git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null) || die "main has no upstream"
  [[ "$upstream" == "origin/main" ]] || die "Expected upstream origin/main, found $upstream"
  git fetch origin main --quiet
  head=$(git rev-parse HEAD)
  [[ "$head" == "$(git rev-parse origin/main)" ]] || die "HEAD is not at origin/main; fetch/push first"
}

assert_generated_release_workflow() {
  if grep -Eq 'actions/(checkout|upload-artifact|download-artifact)@[0-9a-f]{40}' .github/workflows/release.yml; then
    die ".github/workflows/release.yml is generated by cargo-dist and contains pinned action SHAs; regenerate it with the configured dist version"
  fi
  if command -v dist >/dev/null 2>&1; then
    log "Validating cargo-dist configuration"
    dist plan --output-format=json >/dev/null
  else
    log "cargo-dist not installed locally; generated-workflow sanity check only"
  fi
}

assert_ci_green() {
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] Skipping CI green check"
    return 0
  fi
  local sha result status conclusion
  sha=$(git rev-parse HEAD)
  result=$(gh run list --repo "$REPO" --workflow ci.yml --commit "$sha" --limit 1 \
    --json status,conclusion --jq '.[0] | [.status, .conclusion] | @tsv')
  [[ -n "$result" ]] || die "No CI run found for $sha"
  status=${result%%$'\t'*}
  conclusion=${result#*$'\t'}
  [[ "$status" == "completed" && "$conclusion" == "success" ]] || \
    die "CI for $sha is $status/$conclusion"
}

run_gates() {
  log "Running local release gates"
  git diff --check
  npm ci
  npm --prefix node ci
  npm run lint
  npm --prefix node run build
  npm test
  cargo test -p ip-discovery --no-default-features
  cargo test -p ip-discovery --no-default-features --features dns
  cargo test -p ip-discovery --no-default-features --features stun
  cargo test -p ip-discovery --no-default-features --features http
  cargo test -p ip-discovery --no-default-features --features tokio
  RUSTDOCFLAGS='-D warnings' cargo doc --workspace --all-features --no-deps
  cargo deny check
  cargo publish --dry-run -p ip-discovery
}

phase_check() {
  require_commands cargo git gh node npm sed
  validate_version
  assert_versions
  assert_clean_main
  assert_generated_release_workflow
  assert_ci_green
  run_gates
  log "Release checks passed for $VERSION"
}

latest_workflow_run() {
  gh run list --repo "$REPO" --workflow "$WORKFLOW" --branch main --event workflow_dispatch \
    --limit 1 --json databaseId --jq '.[0].databaseId // empty'
}

wait_for_new_run() {
  local previous="$1" run_id="" attempt=0
  while [[ $attempt -lt 30 ]]; do
    run_id=$(latest_workflow_run 2>/dev/null || true)
    if [[ -n "$run_id" && "$run_id" != "$previous" ]]; then
      printf '%s' "$run_id"
      return 0
    fi
    sleep 2
    attempt=$((attempt + 1))
  done
  return 1
}

wait_for_release_run() {
  local tag="$1" previous="$2" run_id="" attempt=0
  while [[ $attempt -lt 60 ]]; do
    run_id=$(gh run list --repo "$REPO" --workflow release.yml --branch "$tag" --limit 1 \
      --json databaseId --jq '.[0].databaseId // empty' 2>/dev/null || true)
    if [[ -n "$run_id" && "$run_id" != "$previous" ]]; then
      printf '%s' "$run_id"
      return 0
    fi
    sleep 2
    attempt=$((attempt + 1))
  done
  return 1
}

validate_bindings_dir() {
  local dir="$1" binding count
  count=$(find "$dir" -maxdepth 1 -type f -name '*.node' | wc -l | tr -d ' ')
  [[ "$count" == 4 ]] || die "Expected 4 Node bindings in $dir, found $count"
  while IFS= read -r binding; do
    [[ -z "$binding" ]] && continue
    [[ -s "$dir/$binding" ]] || die "Missing or empty binding: $binding"
  done <<< "$EXPECTED_BINDINGS"
}

phase_artifacts() {
  local previous run_id binding
  require_commands find gh git node npm
  validate_version
  assert_versions
  assert_clean_main
  if [[ "$DRY_RUN" == true ]]; then
    run_mutation gh workflow run "$WORKFLOW" --repo "$REPO" --ref main
    log "Would wait for the new run, download $NODE_ARTIFACT, validate four targets, and copy them to node/"
    return 0
  fi
  previous=$(latest_workflow_run 2>/dev/null || true)
  gh workflow run "$WORKFLOW" --repo "$REPO" --ref main
  log "Waiting for GitHub Actions run to appear"
  run_id=$(wait_for_new_run "$previous") || die "Timed out waiting for $WORKFLOW run"
  log "Watching run $run_id"
  gh run watch "$run_id" --repo "$REPO" --exit-status
  TEMP_DIR=$(mktemp -d)
  gh run download "$run_id" --repo "$REPO" --name "$NODE_ARTIFACT" --dir "$TEMP_DIR"
  validate_bindings_dir "$TEMP_DIR"
  while IFS= read -r binding; do
    [[ -z "$binding" ]] && continue
    cp -- "$TEMP_DIR/$binding" "node/$binding"
  done <<< "$EXPECTED_BINDINGS"
  validate_bindings_dir node
  printf '%s %s\n' "$VERSION" "$(git rev-parse HEAD)" > node/.bindings-receipt
  npm pack ./node --dry-run
  log "Node bindings from run $run_id are ready"
}

crate_exists() {
  curl --silent --fail --output /dev/null --connect-timeout 5 --max-time 15 \
    --user-agent "$CRATES_USER_AGENT" \
    "https://crates.io/api/v1/crates/$1/$VERSION"
}

npm_exists() {
  npm view "@z0horizon/ip-discovery@$VERSION" version --json >/dev/null 2>&1
}

confirm() {
  local action="$1" answer
  [[ "$YES" == true || "$DRY_RUN" == true ]] && return 0
  printf 'Type "%s %s" to continue: ' "$action" "$VERSION" >&2
  IFS= read -r answer
  [[ "$answer" == "$action $VERSION" ]] || die "Confirmation did not match"
}

wait_for_crate() {
  local crate="$1" attempt=0
  while [[ $attempt -lt 60 ]]; do
    crate_exists "$crate" && return 0
    sleep 5
    attempt=$((attempt + 1))
  done
  return 1
}

publish_crate() {
  local crate="$1"
  if crate_exists "$crate"; then
    log "$crate $VERSION already exists; skipping"
    return 0
  fi
  run_mutation cargo publish --dry-run -p "$crate"
  confirm "publish-$crate"
  run_mutation cargo publish -p "$crate"
  [[ "$DRY_RUN" == true ]] || wait_for_crate "$crate" || die "$crate $VERSION did not become visible on crates.io"
}

publish_npm() {
  if npm_exists; then
    log "npm package $VERSION already exists; skipping"
    return 0
  fi
  [[ "$DRY_RUN" == true ]] || npm whoami >/dev/null
  npm pack ./node --dry-run
  confirm publish-npm
  run_mutation npm publish ./node --access public
}

phase_publish() {
  require_commands cargo curl node npm
  validate_version
  assert_versions
  assert_clean_main
  if [[ "$DRY_RUN" != true ]]; then
    local receipt_file="node/.bindings-receipt"
    [[ -f "$receipt_file" ]] || die "Missing $receipt_file; run 'scripts/release.sh artifacts $VERSION' first"
    local expected_receipt="$VERSION $(git rev-parse HEAD)"
    local actual_receipt
    actual_receipt=$(cat "$receipt_file")
    [[ "$actual_receipt" == "$expected_receipt" ]] || \
      die "Bindings receipt mismatch: expected '$expected_receipt', found '$actual_receipt'. Re-run 'scripts/release.sh artifacts $VERSION'."
  fi
  if [[ "$DRY_RUN" == true ]]; then
    if ! find node -maxdepth 1 -type f -name '*.node' | grep -q .; then
      log "[dry-run] Node bindings not present locally; skipping validate_bindings_dir"
    else
      validate_bindings_dir node
    fi
  else
    validate_bindings_dir node
  fi
  publish_crate ip-discovery
  publish_crate ipd
  publish_npm
  log "All packages published for $VERSION"
}

phase_tag() {
  local tag="v$VERSION" existing previous_run="" run_id=""
  require_commands curl gh git npm
  validate_version
  assert_versions
  assert_clean_main
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] Skipping crates.io and npm existence check"
  else
    crate_exists ip-discovery || die "ip-discovery $VERSION is not on crates.io"
    crate_exists ipd || die "ipd $VERSION is not on crates.io"
    npm_exists || die "npm package $VERSION is not published"
  fi
  existing=$(git ls-remote --tags origin "refs/tags/$tag")
  if [[ -n "$existing" ]]; then
    log "$tag already exists on origin; skipping tag creation"
    previous_run="__none__"
  else
    previous_run=$(gh run list --repo "$REPO" --workflow release.yml --branch "$tag" --limit 1 \
      --json databaseId --jq '.[0].databaseId // empty' 2>/dev/null || true)
    confirm tag
    if git rev-parse "refs/tags/$tag" >/dev/null 2>&1; then
      local tag_commit
      tag_commit=$(git rev-parse "refs/tags/$tag^{commit}")
      [[ "$tag_commit" == "$(git rev-parse HEAD)" ]] || die "Local tag $tag exists but does not point to HEAD"
      log "Local tag $tag already points to HEAD"
    else
      if [[ "$SIGN_TAG" == true ]]; then
        run_mutation git tag -s "$tag" -m "$tag"
      else
        run_mutation git tag -a "$tag" -m "$tag"
      fi
    fi
    run_mutation git push origin "$tag"
  fi
  if [[ "$DRY_RUN" == false ]]; then
    log "Waiting for cargo-dist release workflow"
    run_id=$(wait_for_release_run "$tag" "$previous_run") || die "Timed out waiting for cargo-dist workflow for $tag"
    gh run watch "$run_id" --repo "$REPO" --exit-status
  fi
}

phase_verify() {
  local tag="v$VERSION"
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] Skipping remote verification checks"
    log "Verification passed for $VERSION (dry-run)"
    return 0
  fi
  require_commands curl gh npm
  crate_exists ip-discovery || die "Missing crates.io ip-discovery $VERSION"
  crate_exists ipd || die "Missing crates.io ipd $VERSION"
  npm_exists || die "Missing npm package $VERSION"
  gh release view "$tag" --repo "$REPO" >/dev/null || die "Missing GitHub Release $tag"
  local formula_version
  formula_version=$(gh api -H "Accept: application/vnd.github.v3.raw" "repos/z0horizon/homebrew-tap/contents/Formula/ipd.rb" 2>/dev/null \
    | sed -n 's/^[[:space:]]*version[[:space:]]*"\(.*\)"/\1/p' || true)
  if [[ -n "$formula_version" ]]; then
    [[ "$formula_version" == "$VERSION" ]] || die "Homebrew formula has version $formula_version; expected $VERSION"
  else
    log "Notice: Homebrew tap check skipped or not yet available"
  fi
  log "Verified $VERSION on crates.io, npm, GitHub Releases, and Homebrew"
}

[[ $# -gt 0 ]] || { usage; exit 2; }
COMMAND="$1"
shift
if [[ "$COMMAND" == "-h" || "$COMMAND" == "--help" ]]; then usage; exit 0; fi
[[ $# -gt 0 ]] || die "Version is required"
VERSION="${1#v}"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true ;;
    --yes) YES=true ;;
    --sign-tag) SIGN_TAG=true ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
  shift
done

cd "$(git rev-parse --show-toplevel 2>/dev/null)" || die "Run this inside the repository"

case "$COMMAND" in
  check) phase_check ;;
  artifacts) phase_artifacts ;;
  publish) phase_publish ;;
  tag) phase_tag ;;
  verify) phase_verify ;;
  all)
    phase_check
    phase_artifacts
    phase_publish
    phase_tag
    phase_verify
    ;;
  *) usage; die "Unknown command: $COMMAND" ;;
esac
